version: "3.8"
services:
  mongodb:
    image : mongo:latest
    container_name: mongodb
    #command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATBASE: ml_service_db
    ports:
      - 27017:27017
    volumes:
      - /home/jovik31/storage/mongodb/database:/data/db
      - /home/jovik31/Projects/pyProjects/mlService/database/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped

