version: "3.8"
services:
  mongoDB:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATBASE: ml_service_db
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/internal:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  posgresqlDB:
    image: postgres:latest
    container_name: postgredb
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/internal:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb/init.sql

