// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: proto/file_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message used to stream files between client and server
type FileStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Streams files in chunks, assemble and disassembly at client or server side
	FileChunk []byte `protobuf:"bytes,1,opt,name=fileChunk,proto3" json:"fileChunk,omitempty"`
}

func (x *FileStream) Reset() {
	*x = FileStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStream) ProtoMessage() {}

func (x *FileStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStream.ProtoReflect.Descriptor instead.
func (*FileStream) Descriptor() ([]byte, []int) {
	return file_proto_file_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileStream) GetFileChunk() []byte {
	if x != nil {
		return x.FileChunk
	}
	return nil
}

// Message to request file by name
type RequestFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// File Name
	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
}

func (x *RequestFile) Reset() {
	*x = RequestFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestFile) ProtoMessage() {}

func (x *RequestFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestFile.ProtoReflect.Descriptor instead.
func (*RequestFile) Descriptor() ([]byte, []int) {
	return file_proto_file_service_proto_rawDescGZIP(), []int{1}
}

func (x *RequestFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

// Message that sends files in unary grpc calls
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Files are converted into bytes to be sent and then converted again
	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_file_service_proto_rawDescGZIP(), []int{2}
}

func (x *File) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

// Response message when file is received
type ResponseFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sends file name and the result of the storing operation
	FileName string `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Result   string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResponseFile) Reset() {
	*x = ResponseFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFile) ProtoMessage() {}

func (x *ResponseFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFile.ProtoReflect.Descriptor instead.
func (*ResponseFile) Descriptor() ([]byte, []int) {
	return file_proto_file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseFile) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ResponseFile) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_file_service_proto protoreflect.FileDescriptor

var file_proto_file_service_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x0a, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65,
	0x43, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x66, 0x69, 0x6c,
	0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x22, 0x29, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x1a, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x69, 0x6c,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x42, 0x0a,
	0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0xb3, 0x01, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x66, 0x65,
	0x72, 0x12, 0x2e, 0x0a, 0x0c, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x0d,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x00, 0x28,
	0x01, 0x12, 0x2f, 0x0a, 0x0e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x1a, 0x0b, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x20, 0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x05, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x1a, 0x0d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x46, 0x69,
	0x6c, 0x65, 0x22, 0x00, 0x12, 0x21, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x0c, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x1a, 0x05,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_file_service_proto_rawDescOnce sync.Once
	file_proto_file_service_proto_rawDescData = file_proto_file_service_proto_rawDesc
)

func file_proto_file_service_proto_rawDescGZIP() []byte {
	file_proto_file_service_proto_rawDescOnce.Do(func() {
		file_proto_file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_file_service_proto_rawDescData)
	})
	return file_proto_file_service_proto_rawDescData
}

var file_proto_file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_file_service_proto_goTypes = []interface{}{
	(*FileStream)(nil),   // 0: FileStream
	(*RequestFile)(nil),  // 1: RequestFile
	(*File)(nil),         // 2: File
	(*ResponseFile)(nil), // 3: ResponseFile
}
var file_proto_file_service_proto_depIdxs = []int32{
	0, // 0: FileTranfer.UploadStream:input_type -> FileStream
	1, // 1: FileTranfer.DownloadStream:input_type -> RequestFile
	2, // 2: FileTranfer.Upload:input_type -> File
	1, // 3: FileTranfer.Download:input_type -> RequestFile
	3, // 4: FileTranfer.UploadStream:output_type -> ResponseFile
	0, // 5: FileTranfer.DownloadStream:output_type -> FileStream
	3, // 6: FileTranfer.Upload:output_type -> ResponseFile
	2, // 7: FileTranfer.Download:output_type -> File
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_file_service_proto_init() }
func file_proto_file_service_proto_init() {
	if File_proto_file_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_file_service_proto_goTypes,
		DependencyIndexes: file_proto_file_service_proto_depIdxs,
		MessageInfos:      file_proto_file_service_proto_msgTypes,
	}.Build()
	File_proto_file_service_proto = out.File
	file_proto_file_service_proto_rawDesc = nil
	file_proto_file_service_proto_goTypes = nil
	file_proto_file_service_proto_depIdxs = nil
}
