# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x66ile_service.proto\"\x1b\n\x07Request\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"&\n\x04\x46ile\x12\x0c\n\x04\x66ile\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\",\n\x08Response\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2N\n\x0b\x46ileTranfer\x12\x1e\n\x06Upload\x12\x05.File\x1a\t.Response\"\x00(\x01\x12\x1f\n\x08\x44ownload\x12\x08.Request\x1a\x05.File\"\x00\x30\x01\x42\x0bZ\t./go_grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t./go_grpc'
  _globals['_REQUEST']._serialized_start=22
  _globals['_REQUEST']._serialized_end=49
  _globals['_FILE']._serialized_start=51
  _globals['_FILE']._serialized_end=89
  _globals['_RESPONSE']._serialized_start=91
  _globals['_RESPONSE']._serialized_end=135
  _globals['_FILETRANFER']._serialized_start=137
  _globals['_FILETRANFER']._serialized_end=215
# @@protoc_insertion_point(module_scope)
