// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: file_service.proto

package go_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FileTranferClient is the client API for FileTranfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileTranferClient interface {
	// Upload file using unary grpc for files smaller than 4mb.
	Upload(ctx context.Context, opts ...grpc.CallOption) (FileTranfer_UploadClient, error)
	// Upload file using unary grpc for files smaller than 4mb
	Download(ctx context.Context, in *Request, opts ...grpc.CallOption) (FileTranfer_DownloadClient, error)
}

type fileTranferClient struct {
	cc grpc.ClientConnInterface
}

func NewFileTranferClient(cc grpc.ClientConnInterface) FileTranferClient {
	return &fileTranferClient{cc}
}

func (c *fileTranferClient) Upload(ctx context.Context, opts ...grpc.CallOption) (FileTranfer_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileTranfer_ServiceDesc.Streams[0], "/FileTranfer/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTranferUploadClient{stream}
	return x, nil
}

type FileTranfer_UploadClient interface {
	Send(*File) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type fileTranferUploadClient struct {
	grpc.ClientStream
}

func (x *fileTranferUploadClient) Send(m *File) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileTranferUploadClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileTranferClient) Download(ctx context.Context, in *Request, opts ...grpc.CallOption) (FileTranfer_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileTranfer_ServiceDesc.Streams[1], "/FileTranfer/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTranferDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileTranfer_DownloadClient interface {
	Recv() (*File, error)
	grpc.ClientStream
}

type fileTranferDownloadClient struct {
	grpc.ClientStream
}

func (x *fileTranferDownloadClient) Recv() (*File, error) {
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FileTranferServer is the server API for FileTranfer service.
// All implementations must embed UnimplementedFileTranferServer
// for forward compatibility
type FileTranferServer interface {
	// Upload file using unary grpc for files smaller than 4mb.
	Upload(FileTranfer_UploadServer) error
	// Upload file using unary grpc for files smaller than 4mb
	Download(*Request, FileTranfer_DownloadServer) error
	mustEmbedUnimplementedFileTranferServer()
}

// UnimplementedFileTranferServer must be embedded to have forward compatible implementations.
type UnimplementedFileTranferServer struct {
}

func (UnimplementedFileTranferServer) Upload(FileTranfer_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedFileTranferServer) Download(*Request, FileTranfer_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedFileTranferServer) mustEmbedUnimplementedFileTranferServer() {}

// UnsafeFileTranferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileTranferServer will
// result in compilation errors.
type UnsafeFileTranferServer interface {
	mustEmbedUnimplementedFileTranferServer()
}

func RegisterFileTranferServer(s grpc.ServiceRegistrar, srv FileTranferServer) {
	s.RegisterService(&FileTranfer_ServiceDesc, srv)
}

func _FileTranfer_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTranferServer).Upload(&fileTranferUploadServer{stream})
}

type FileTranfer_UploadServer interface {
	SendAndClose(*Response) error
	Recv() (*File, error)
	grpc.ServerStream
}

type fileTranferUploadServer struct {
	grpc.ServerStream
}

func (x *fileTranferUploadServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileTranferUploadServer) Recv() (*File, error) {
	m := new(File)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileTranfer_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileTranferServer).Download(m, &fileTranferDownloadServer{stream})
}

type FileTranfer_DownloadServer interface {
	Send(*File) error
	grpc.ServerStream
}

type fileTranferDownloadServer struct {
	grpc.ServerStream
}

func (x *fileTranferDownloadServer) Send(m *File) error {
	return x.ServerStream.SendMsg(m)
}

// FileTranfer_ServiceDesc is the grpc.ServiceDesc for FileTranfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileTranfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FileTranfer",
	HandlerType: (*FileTranferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _FileTranfer_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _FileTranfer_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "file_service.proto",
}
